### ISSUE TITLE
GitHub setup

### ISSUE THREAD

**Issue by MrAwesome2127** [MrAwesome2127/KU-Project3-FinalProject#28]
Create a Secret Variable for Render

> "secrets.RENDER_DEPLOY_HOOK_URL"

Create yml file

```
name: Deploy to Render

on:
  push:
    branches: [main]
  pull_request:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: | 
          curl "$DEPLOY_URL"

```
